### ISSUE TITLE
IMPACT OSS logo

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-tasks#2]
The IMPACT OSS project logo

**Comment by tmfrnz** [comment]
### Brief (draft)

#### Objective
To represent IMPACT OSS and its purpose to promote Human Rights by developing effective tools


#### Name
“IMPACT OSS”


#### Tagline
“Integrated Management and Planning of Actions”

#### Deliverables
- Standalone version with name only 
- Full version with tagline


#### Target Audience
The target audience include users, partners and donors of IMPACT OSS, specifically
- Primary audience: National Mechanisms for Reporting and Followups (part of national governments)
- Secondary audience: National Human Rights Institutions, other international Human Rights organisations (such as URG, OHCHR)

Further the target audience may also include potential collaborators and contributors to the open source software, specifically 
- Open source software developers 
 
#### Usage

To be used on all outputs of the IMPACT OSS group, 

Digital outputs:
- IMPACT OSS project website 
- Header of IMPACT OSS demo site
- Footer of IMPACT OSS custom implementations

- Software manual and documentation
- Demo video
- Presentations, including workshops
- Email
- Newsletter

Print outputs:
- Promotional brochures
- Flyer

#### Design requirements
- Logo suitable for small and large display
- Accessible colours

#### Keywords
- Modern
- Clean 
- Open
- Objective
- Trustworthy
- Authoritative
- Accessible
- Equality
- Not-for-profit

#### Concepts and inspiration
- Impact
- Actions
- Connectivity
- Synergy
- Human Rights
- Reporting
- Typographic/lettermark


#### Other considerations
- Will inform design of base theme (#4) and demo site (#6)

**Comment by tmfrnz** [comment]
#### Proposal
Please find our proposal attached
[P-17005_IMPACT_Logo.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555163b0929ba3190077e4da/125516c66e82c728ace21e0d46d8d9cb74d2d3fcb0c09273857ec4ab0549207c6b48e13b628ae92dbc56395b4d5a47f9450c0945f5aa8a2ef7b634708a090dbcd16f0926c32f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e7838a463f1c051f8ffe5b27ed.pdf)

**Comment by ashbowe** [comment]
Approved
