### ISSUE TITLE
Base theme

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-tasks#4]
### Specification

Develop a neutral base theme to be used
- as a starting point for any country specific theme customisation
- for the demo site (#6)

The base theme will include
- icons for the main entities (such as actions and recommendations) and the most common global taxonomies
- the IMPACT OSS logo (#2)

Requirements
- colors should be carefully chosen under careful consideration of the latest web accessibility guidelines

**Comment by tmfrnz** [comment]
### Proposal

Please find our proposal attached
[P-17003_IMPACT_BaseTheme.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555163b0929ba3190077e4da/125516c66e82c728ace21e0d46d8d9cb74d2d3fab0c09273857ec4ab0b4734761d0ca62675c7af6aaf50740b0a0c0abe4b4a5a4da9fddd7da7bf6f738f0d0be5d16d0a72973d13faea870da313f871d51bdaebe5c01982fa3737e68c854e3b1e0d1a8efd5c37a1994ccf4abb.pdf)

**Comment by ashbowe** [comment]
Approved
