### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-tasks#6]
- Demo site set up and content entry

**Comment by tmfrnz** [comment]
### Specification (draft)

#### Purpose

A demo site is required to showcase the functionality of the application.

#### Requirements

The demo site should 
- feature the base theme (see #4)
- allow users to log in using any of the available roles

The database should be set up with 
- the common global taxonomies, as well as at least one other sample custom taxonomy
- sample data for actions and recommendations, categorised with avialable taxonomies
- the global SDG targets and indicators
- users for each role (guest, contributor, manager, admin)

In addition it should be considered to limit the functionality to prevent abuse, eg not allowing users on the demo site to change email addresses.

#### Maintenance

Further it will be required to 
- frequently monitor the demo site
- periodically reset the demo database

#### Hosting

Finally the demo site will require hosting.

**Comment by tmfrnz** [comment]
### Proposal
Please find our proposal attached
[P-17006_IMPACT_DemoSite.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555163b0929ba3190077e4da/125516c66e82c728ace21e0d46d8d9cb74d2d3ffb0c09273857ec4ab0d432a7c1a0db72e32c9a138ad4d71040c1b5ca6535d5611f8addf2aafe53f75db5c03edd1385925c63f47febd9003ad43eb7edf10d8eff6df0ed2e22f27e5818e4a3e1600118bfa5f32a1914dda15.pdf)

**Comment by ashbowe** [comment]
Looks good - gets my approval

**Comment by tmfrnz** [comment]
## Tasks

### Email
- Set up email addresses
  - contact@impactoss.org
  - admin@impactoss.org

### Heroku
- create new Heroku app
- connect with GitHub repository
- add Heroku Postgres database
- add Mailgun
- set config variables
- deploy
- add domain with SSL: api.impactoss.org (requires paid dyno)

### AWS
- create account for admin@impactoss.org 
- set up S3 bucket
